language: node_js

node_js:
  - "iojs"
  - "node"
  - "4.1"
  - "0.12"
  - "0.8"

matrix:
  allow_failures:
  # looks broken on travis-ci itself
  - node_js: "0.8"

notifications:
  email:
    on_failure: always # [always|never|change] default: always

before_script:
  - "export PATH=node_modules/.bin:node_modules/easy-bake/node_modules/.bin:$PATH"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
