library:
  join: lifecycle.js
  compress: true
  files:
    - src/**/*.coffee

tests:
  output: build
  directories:
    - test/core
    - test/packaging
  options:
    test:
      command: phantomjs
      runner: phantomjs-qunit-runner.js
      files:
        - '**/*.html'
    build:
      no_files_ok: ['test/packaging']
